version: '3.9'

services:
  unidev-front:
    container_name: unidev-front
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANGULAR_CONFIGURATION: production
    image: unidev-front:latest
    ports:
      - '8080:80'
    environment:
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
